FROM continuumio/miniconda3

WORKDIR /home/app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

CMD uvicorn app:app --reload

# docker build . -t api_mam
# docker run -it -v "$(pwd):/home/app" api_mam
# https://docs.docker.com/get-started/04_sharing_app/






